"""Standalone clinical review page. Decisions remain local until exported/imported."""
import json
from pathlib import Path
from approval import fingerprint

def write_review_page(bank, root):
    payload = dict(bank)
    payload['fingerprints'] = {q['id']: {lc: fingerprint(q,[lc]) for lc in q['content']} for q in bank['questions']}
    encoded=json.dumps(payload,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')
    (Path(root)/'pruefung.html').write_text(TEMPLATE.replace('@@BANK@@',encoded),encoding='utf-8')

TEMPLATE=r'''<!doctype html>
<html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Urofragen · Fachliche Prüfung</title>
<style>
:root{font-family:system-ui,sans-serif;color:#163038;background:#f2f5f4;line-height:1.55}*{box-sizing:border-box}body{max-width:1060px;margin:auto;padding:24px}h1{font-size:clamp(26px,4vw,38px);margin:10px 0}h2{font-size:23px}a{color:#08675d}.card{background:white;border:1px solid #dce5e1;border-radius:16px;padding:24px;margin:18px 0}.row{display:flex;gap:14px;flex-wrap:wrap;align-items:end}label{display:flex;flex-direction:column;gap:5px;flex:1;min-width:150px;font-weight:600}input,select,textarea,button{font:inherit;border:1px solid #b7c8c1;border-radius:9px;padding:11px;background:white;color:inherit}textarea{width:100%;min-height:110px;resize:vertical}button{cursor:pointer;font-weight:650}button:disabled{opacity:.4;cursor:default}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #cf8300;outline-offset:3px}.yes{background:#08675d;color:white;border-color:#08675d}.no{border:2px solid #ad3e30;color:#923426}.muted{color:#536a6f;font-size:.93rem}.option{border-left:4px solid #c8d4d0;padding:12px 16px;margin:12px 0;background:#f7f9f8}.correct{border-color:#087d66;background:#eef9f4}.badge{display:inline-block;background:#e4f0eb;border-radius:7px;padding:4px 9px}.notice{background:#fff6dc;padding:12px;border-radius:8px}#feedback{min-height:28px;font-weight:600;white-space:pre-wrap}.actions{margin-top:16px}.sources{overflow-wrap:anywhere}pre{white-space:pre-wrap}#position{margin-right:auto}progress{width:100%;height:12px}button.active{box-shadow:0 0 0 3px #e8bd5a}#review-title{scroll-margin-top:15px}@media(max-width:600px){body{padding:12px}.card{padding:17px}.actions button{width:100%}}
</style>
<header><a href="index.html" id="back"></a><h1 id="title"></h1><p id="intro"></p></header>
<section class="card" aria-label="Settings"><div class="row">
<label><span id="name-label"></span><input id="name" autocomplete="name"></label>
<label><span id="language-label"></span><select id="language"><option value="de">Deutsch</option><option value="en">English</option><option value="es">Español</option></select></label>
<label><span id="expiry-label"></span><input type="date" id="expiry"></label></div>
<p class="muted" id="scope"></p><div class="row"><label><span id="domain-label"></span><select id="domain"></select></label><label><span id="filter-label"></span><select id="filter"></select></label></div>
<p id="summary"></p><progress id="progress" max="214" value="0"></progress>
<div class="row"><button id="export"></button><label><span id="restore-label"></span><input type="file" id="restore" accept="application/json,.json"></label></div><p class="muted" id="storage"></p></section>
<div class="row"><span id="position"></span><button id="prev"></button><button id="next"></button></div>
<main id="question" class="card"></main><p id="feedback" role="status" aria-live="polite"></p>
<script id="bank" type="application/json">@@BANK@@</script>
<script>
'use strict';
const BANK=JSON.parse(document.getElementById('bank').textContent),KEY='urofragen-clinical-review-v1';
const TEXT={
de:{back:'← Zum Lernmodus',title:'Fachliche Prüfung',intro:'Prüfe Frage, richtige Antwort und jede Begründung. Setze danach einen Haken oder markiere den Korrekturbedarf.',name:'Dein Name als Prüfer',expiry:'Freigabe gültig bis',language:'Geprüfte Sprache',scope:'✓ bestätigt nur diese Fragenversion in der angezeigten Sprache einschließlich Lösung und Begründungen. Die spanische und englische Fassung werden separat geprüft.',domain:'Abschnitt',all:'Alle Abschnitte',filter:'Anzeigen',filters:['Alle Fragen','Noch offen','✓ Fachlich korrekt','✗ Korrektur nötig'],export:'Prüfungen als Datei sichern',restore:'Gesicherte Prüfungen laden',storage:'Speicherung in diesem Browser. Sichere die Datei nach jeder Sitzung. Erst die Übernahme der exportierten Prüfungen aktualisiert die Lernwebsite.',prev:'← Zurück',next:'Weiter →',empty:'Keine Fragen in dieser Auswahl.',correct:'Richtige Antwort',reason:'Begründung',core:'Kernaussage',teaching:'Merksatz',sources:'Quellen',note:'Was stimmt nicht? / Anmerkung',placeholder:'Zum Beispiel: Option B ist ebenfalls vertretbar, weil …',yes:'✓ Fachlich korrekt',no:'✗ Korrektur nötig',reset:'Entscheidung zurücknehmen',open:'Noch nicht geprüft',approved:'✓ Fachlich korrekt',changes_requested:'✗ Korrektur nötig',saved:'Gespeichert. Du kannst mit „Weiter“ fortfahren.',requiredName:'Bitte zuerst deinen Prüfernamen eintragen.',requiredNote:'Bitte beschreibe kurz, was korrigiert werden muss.',requiredDate:'Bitte ein gültiges Ablaufdatum ab heute wählen.',failed:'Speichern fehlgeschlagen. Sichere jetzt die Prüfdatei; die Entscheidung ist nur vorübergehend im Arbeitsspeicher.',stale:'Eine ältere Entscheidung passt nicht mehr zu Version, Inhalt oder Gültigkeit. Bitte erneut prüfen.',summary:'Prüfstand dieser Sprache',pending:'offen',version:'Version',of:'von',downloaded:'Prüfdatei heruntergeladen. Du kannst sie zur Übernahme der Entscheidungen weitergeben.',imported:'Prüfdatei geladen. Neuere lokale Entscheidungen wurden behalten.',badFile:'Die Datei enthält keine passenden gültigen Prüfdatensätze.',confirm:'Geänderte Anmerkung ist noch nicht gespeichert. Ohne Speichern fortfahren?',noteDirty:'Anmerkung geändert: Bitte ✓ oder ✗ zum Speichern anklicken.',local:'Lokal dokumentiert',noDecisions:'Noch keine Entscheidungen zum Exportieren.',flag:'Evidenzhinweis',missingSource:'Kein direkter Link im Fragenbestand hinterlegt.'},
en:{back:'← Learning mode',title:'Clinical review',intro:'Review the question, correct answer and every rationale. Then approve it or mark it for correction.',name:'Your name as reviewer',expiry:'Approval valid until',language:'Language being reviewed',scope:'✓ approves only this question version in the displayed language, including the answer and rationales. Other languages require separate review.',domain:'Section',all:'All sections',filter:'Show',filters:['All questions','Pending','✓ Clinically correct','✗ Correction needed'],export:'Save reviews to file',restore:'Load saved reviews',storage:'Stored in this browser. Save a file after each session. The learning website is updated only after the exported decisions are incorporated.',prev:'← Previous',next:'Next →',empty:'No questions match these filters.',correct:'Correct answer',reason:'Rationale',core:'Core explanation',teaching:'Teaching point',sources:'Sources',note:'What needs correcting? / Comment',placeholder:'For example: Option B is also defensible because …',yes:'✓ Clinically correct',no:'✗ Correction needed',reset:'Withdraw decision',open:'Not reviewed yet',approved:'✓ Clinically correct',changes_requested:'✗ Correction needed',saved:'Saved. Use “Next” to continue.',requiredName:'Please enter your reviewer name first.',requiredNote:'Please describe what needs correcting.',requiredDate:'Choose a valid expiry date from today onwards.',failed:'Saving failed. Export your review file now; the decision is only held temporarily in memory.',stale:'An older decision no longer matches the version, content or validity period. Review again.',summary:'Progress for this language',pending:'pending',version:'Version',of:'of',downloaded:'Review file downloaded. You can send it for incorporation.',imported:'Review file loaded. Newer local decisions were kept.',badFile:'This file contains no matching valid review records.',confirm:'Your edited comment is not saved. Continue without saving?',noteDirty:'Comment changed: click ✓ or ✗ to save.',local:'Recorded locally',noDecisions:'No decisions to export yet.',flag:'Evidence note',missingSource:'No direct link is provided in the question bank.'},
es:{back:'← Modo de aprendizaje',title:'Revisión clínica',intro:'Revisa la pregunta, la respuesta correcta y cada justificación. Después, aprueba la pregunta o indica que necesita corrección.',name:'Tu nombre como revisor',expiry:'Aprobación válida hasta',language:'Idioma que se revisa',scope:'✓ aprueba solo esta versión de la pregunta en el idioma mostrado, incluidas la respuesta y las justificaciones. Los otros idiomas requieren una revisión independiente.',domain:'Sección',all:'Todas las secciones',filter:'Mostrar',filters:['Todas las preguntas','Pendientes','✓ Clínicamente correcta','✗ Necesita corrección'],export:'Guardar revisiones en un archivo',restore:'Cargar revisiones guardadas',storage:'Se guarda en este navegador. Descarga una copia después de cada sesión. La web de aprendizaje se actualiza cuando se incorporan las decisiones exportadas.',prev:'← Anterior',next:'Siguiente →',empty:'No hay preguntas con estos filtros.',correct:'Respuesta correcta',reason:'Justificación',core:'Explicación principal',teaching:'Punto clave',sources:'Fuentes',note:'¿Qué debe corregirse? / Comentario',placeholder:'Por ejemplo: La opción B también es defendible porque …',yes:'✓ Clínicamente correcta',no:'✗ Necesita corrección',reset:'Retirar decisión',open:'Aún no revisada',approved:'✓ Clínicamente correcta',changes_requested:'✗ Necesita corrección',saved:'Guardado. Pulsa «Siguiente» para continuar.',requiredName:'Introduce primero tu nombre como revisor.',requiredNote:'Describe brevemente qué debe corregirse.',requiredDate:'Elige una fecha de caducidad válida a partir de hoy.',failed:'No se pudo guardar. Exporta el archivo ahora; la decisión solo está temporalmente en la memoria.',stale:'Una decisión anterior ya no coincide con la versión, el contenido o el período de validez. Revisa de nuevo.',summary:'Progreso de este idioma',pending:'pendientes',version:'Versión',of:'de',downloaded:'Archivo descargado. Puedes enviarlo para incorporar las decisiones.',imported:'Archivo cargado. Se han conservado las decisiones locales más recientes.',badFile:'El archivo no contiene registros de revisión válidos para estas preguntas.',confirm:'El comentario modificado no está guardado. ¿Continuar sin guardarlo?',noteDirty:'Comentario modificado: pulsa ✓ o ✗ para guardarlo.',local:'Registrado localmente',noDecisions:'Todavía no hay decisiones para exportar.',flag:'Nota sobre la evidencia',missingSource:'No hay un enlace directo en el banco de preguntas.'}
};
const $=id=>document.getElementById(id),today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
let state={schema:'urofragen-clinical-review-v1',reviewer:'',language:'de',decisions:{}},lang='de',list=[],index=0,dirty=false,storageError=false;
try{let s=JSON.parse(localStorage.getItem(KEY));if(s&&s.schema===state.schema&&s.decisions&&typeof s.decisions==='object')state=s;}catch(e){storageError=true;}
lang=TEXT[state.language]?state.language:'de';const tr=()=>TEXT[lang];
function message(s){$('feedback').textContent=s;}
function key(q,lc=lang){return q.id+':'+lc;}
function valid(d,q,lc=lang){return !!d&&d.question_id===q.id&&d.question_version===q.version&&d.language===lc&&d.content_sha256===BANK.fingerprints[q.id][lc]&&['approved','changes_requested'].includes(d.decision)&&(d.decision!=='approved'||d.expires>=today());}
function decision(q){let d=state.decisions[key(q)];return valid(d,q)?d:null;}
function persist(){state.reviewer=$('name').value.trim();state.language=lang;try{localStorage.setItem(KEY,JSON.stringify(state));storageError=false;return true;}catch(e){storageError=true;return false;}}
function safeLeave(){if(!dirty)return true;if(!window.confirm(tr().confirm))return false;dirty=false;return true;}
function node(tag,text,cls){let n=document.createElement(tag);n.textContent=text||'';if(cls)n.className=cls;return n;}
function summary(){let qs=BANK.questions,yes=qs.filter(q=>decision(q)?.decision==='approved').length,no=qs.filter(q=>decision(q)?.decision==='changes_requested').length;$('summary').textContent=`${tr().summary}: ${yes} ✓ · ${no} ✗ · ${qs.length-yes-no} ${tr().pending}`;$('progress').max=qs.length;$('progress').value=yes+no;}
function configure(){document.documentElement.lang=lang;document.title='Urofragen · '+tr().title;for(const [id,k] of Object.entries({back:'back',title:'title',intro:'intro','name-label':'name','expiry-label':'expiry','language-label':'language',scope:'scope','domain-label':'domain','filter-label':'filter',export:'export','restore-label':'restore',storage:'storage',prev:'prev',next:'next'}))$(id).textContent=tr()[k];let domain=$('domain').value,filter=$('filter').value;$('domain').replaceChildren(new Option(tr().all,''));BANK.domains.forEach(d=>$('domain').add(new Option(d.label[lang],d.slug)));$('domain').value=domain;$('filter').replaceChildren();['all','pending','approved','changes_requested'].forEach((v,i)=>$('filter').add(new Option(tr().filters[i],v)));$('filter').value=filter||'all';$('language').value=lang;summary();}
function selectList(preferred){list=BANK.questions.filter(q=>(!$('domain').value||q.taxonomy.domain===$('domain').value)&&($('filter').value==='all'||($('filter').value==='pending'?!decision(q):decision(q)?.decision===$('filter').value)));index=Math.max(0,list.findIndex(q=>q.id===preferred));render();}
function render(){dirty=false;summary();const root=$('question');root.replaceChildren();$('prev').disabled=index<=0;$('next').disabled=index>=list.length-1;$('position').textContent=list.length?`${index+1} ${tr().of} ${list.length}`:'';if(!list.length){root.append(node('p',tr().empty));return;}const q=list[index],b=q.content[lang],d=decision(q);root.append(node('p',`${q.id} · ${tr().version} ${q.version} · ${lang.toUpperCase()}`,'muted'));const status=node('p',d?`${tr()[d.decision]} · ${d.reviewer} · ${d.date} · ${tr().local}`:tr().open,'badge');root.append(status);if(state.decisions[key(q)]&&state.decisions[key(q)].decision!=='withdrawn'&&!d)root.append(node('p',tr().stale,'notice'));const title=node('h2',b.lead_in);title.id='review-title';root.append(node('p',b.vignette),title);for(const o of q.options){const item=b.options[o.key],box=node('section','','option'+(o.correct?' correct':''));box.append(node('strong',`${o.key}. ${item.text}${o.correct?' — ✓ '+tr().correct:''}`),node('p',tr().reason+': '+item.rationale));root.append(box);}root.append(node('h3',tr().core),node('p',b.explanation.core),node('h3',tr().teaching),node('p',b.explanation.teaching_point));if(b.flag_note)root.append(node('p',tr().flag+': '+b.flag_note,'notice'));root.append(node('h3',tr().sources));for(const s of q.sources){const p=node('p',`${s.title||s.citation||s.code||''} (${s.year||''}) `,'sources');if(s.url&&/^https?:\/\//i.test(s.url)){const a=node('a',s.url);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';p.append(a);}else p.append(node('span',tr().missingSource,'muted'));root.append(p);}const label=node('label',tr().note),note=node('textarea');note.id='note';note.placeholder=tr().placeholder;note.value=d?.note||'';note.addEventListener('input',()=>{dirty=true;message(tr().noteDirty);});label.append(note);root.append(label);const actions=node('div','','row actions');for(const [status,k,cls] of [['approved','yes','yes'],['changes_requested','no','no'],['withdrawn','reset','']]){const button=node('button',tr()[k],cls+(d?.decision===status?' active':''));button.type='button';button.setAttribute('aria-pressed',String(d?.decision===status));button.addEventListener('click',()=>save(status));actions.append(button);}const advance=node('button',tr().next);advance.disabled=index>=list.length-1;advance.addEventListener('click',()=>{if(!safeLeave())return;index++;render();message('');$('question').scrollIntoView({behavior:'smooth',block:'start'});});actions.append(advance);root.append(actions);$('expiry').value=d?.expires||q.review.expires;$('expiry').min=today();}
function save(status){const q=list[index],reviewer=$('name').value.trim(),note=$('note').value.trim(),expires=$('expiry').value;if(!reviewer){message(tr().requiredName);$('name').focus();return;}if(status==='changes_requested'&&!note){message(tr().requiredNote);$('note').focus();return;}if(status==='approved'&&(!/^\d{4}-\d{2}-\d{2}$/.test(expires)||!Number.isFinite(Date.parse(expires))||expires<today())){message(tr().requiredDate);$('expiry').focus();return;}const previous=state.decisions[key(q)];state.decisions[key(q)]={question_id:q.id,question_version:q.version,language:lang,content_sha256:BANK.fingerprints[q.id][lang],reviewer,date:today(),updated_at:new Date().toISOString(),expires:status==='approved'?expires:null,decision:status,note,history:previous?[...(previous.history||[]),Object.fromEntries(Object.entries(previous).filter(([k])=>k!=='history'))]:[]};dirty=false;const saved=persist();render();message(saved?tr().saved:tr().failed);}
$('name').value=state.reviewer||'';
$('name').addEventListener('change',()=>{if(!persist())message(tr().failed);});
$('language').addEventListener('change',()=>{if(!safeLeave()){$('language').value=lang;return;}let id=list[index]?.id;lang=$('language').value;configure();selectList(id);if(!persist())message(tr().failed);else message('');});
let previousDomain='',previousFilter='all';for(const id of ['domain','filter'])$(id).addEventListener('change',()=>{if(!safeLeave()){$('domain').value=previousDomain;$('filter').value=previousFilter;return;}previousDomain=$('domain').value;previousFilter=$('filter').value;selectList();message('');});
for(const [id,delta] of [['prev',-1],['next',1]])$(id).addEventListener('click',()=>{if(!safeLeave())return;index=Math.max(0,Math.min(list.length-1,index+delta));render();message('');$('question').scrollIntoView({behavior:'smooth',block:'start'});});
$('export').addEventListener('click',()=>{if(!safeLeave())return;if(!Object.keys(state.decisions).length){message(tr().noDecisions);return;}const payload={...state,exported_at:new Date().toISOString(),bank_generated:BANK.generated};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='Urofragen-Pruefung-'+today()+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);message(tr().downloaded);});
$('restore').addEventListener('change',async()=>{const file=$('restore').files[0];if(!file)return;if(!safeLeave()){$('restore').value='';return;}try{const data=JSON.parse(await file.text());if(data.schema!==state.schema||!data.decisions)throw Error();let count=0;for(const [k,d] of Object.entries(data.decisions)){const q=BANK.questions.find(q=>q.id===d.question_id);if(!q||!TEXT[d.language]||k!==key(q,d.language)||!['approved','changes_requested','withdrawn'].includes(d.decision)||typeof d.reviewer!=='string'||!d.reviewer.trim()||typeof d.note!=='string'||!Number.isFinite(Date.parse(d.updated_at))||d.content_sha256!==BANK.fingerprints[q.id][d.language]||d.question_version!==q.version||!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||(d.decision==='changes_requested'&&!d.note.trim())||(d.decision==='approved'&&(!/^\d{4}-\d{2}-\d{2}$/.test(d.expires)||d.expires<d.date)))continue;const old=state.decisions[k];if(!old||Date.parse(d.updated_at)>Date.parse(old.updated_at))state.decisions[k]={...d,history:Array.isArray(d.history)?d.history:[]};count++;}if(!count)throw Error();const saved=persist();selectList(list[index]?.id);message(saved?tr().imported:tr().failed);}catch(e){message(tr().badFile);}finally{$('restore').value='';}});
window.addEventListener('beforeunload',e=>{if(dirty||storageError){e.preventDefault();e.returnValue='';}});
configure();selectList();if(storageError)message(tr().failed);
</script></html>'''
